# Generated by Django 4.1.7 on 2023-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cartitem_amount_alter_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
