# Generated by Django 4.1.7 on 2023-03-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_coupon_amount_alter_coupon_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='date_sent',
        ),
    ]
