# Generated by Django 4.1.7 on 2023-03-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cart_coupon_remove_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='coupon',
        ),
    ]
