# Generated by Django 4.1.7 on 2023-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_original',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
