# Generated by Django 4.1.7 on 2023-04-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='profit_order',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
