# Generated by Django 4.2 on 2023-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders_profit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
    ]
