# Generated by Django 4.2 on 2023-04-22 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='logo/default_logo.png', max_length=255, null=True, verbose_name='brand_logo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='customer_image/default_dvapof.jpg', max_length=255, null=True, verbose_name='customer_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
