# Generated by Django 4.1.7 on 2023-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_contact_feedback_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
