# Generated by Django 4.1.7 on 2023-04-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_coupon_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount',
            new_name='sub_total',
        ),
    ]
