# Generated by Django 4.1.7 on 2023-04-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
