# Generated by Django 4.1.7 on 2023-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cartitem_coupon_cartitem_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
