# Generated by Django 4.1.7 on 2023-04-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_cartitem_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='amount',
            new_name='sub_total',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='coupon',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.coupon'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='coupon_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deliveryaddress'),
        ),
    ]
