# Generated by Django 4.1.7 on 2023-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_orders_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Online Payment', 'Online Payment'), ('Bank Transfer', 'Bank Transfer'), ('Paypal', 'Paypal'), ('Visa', 'Visa'), ('Master Card', 'Master Card'), ('Payonner', 'Payonner'), ('Masetro', 'Masetro'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50, null=True),
        ),
    ]
