# Generated by Django 4.1.7 on 2023-04-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_orders_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='sub_total',
        ),
    ]
