# Generated by Django 4.1.7 on 2023-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_orders_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
