# Generated by Django 4.1.7 on 2023-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_orders_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
