# Generated by Django 4.1.7 on 2023-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_rates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
