# Generated by Django 4.1.7 on 2023-04-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_product_num_of_rates_product_total_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_of_rates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_rate',
        ),
    ]
