# Generated by Django 4.1.7 on 2023-04-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_product_review_count_product_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review_rate',
            new_name='review_rate_agv',
        ),
    ]
