# Generated by Django 4.1.7 on 2023-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_review_rate_product_review_rate_agv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_rate_agv',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.BooleanField(default=True),
        ),
    ]
