# Generated by Django 4.1.7 on 2023-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_product_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='review_rate_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
